django_intro/urls.py
from django.contrib import admin
from django.urls import path, re_path
from intro.views import get_todo_list, create_item, edit_item, toggle_status

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', get_todo_list),
    path('add', create_item),
 #   re_path(r'^edit/(?P<id>\d+)$', edit_item),
    path('edit/<int:id>',edit_item),
    path('toggle/<int:id>', toggle_status)
]

intro/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=30, blank=False)
    done = models.BooleanField(blank=False, default=False)
    
    def __str__(self):
        return self.name

intro/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'done')

intro/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from .models import Item
from .forms import ItemForm

# Create your views here.
def get_todo_list(request):
    results = Item.objects.all()
    return render(request, "todo_list.html", {
        'items': results
    })
    
def create_item(request):
    if request.method == "POST":
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(get_todo_list)
    else:
        form = ItemForm()

    return render(request, "item_form.html", {'form': form})
    
#   Replaced by django form in side if statement     
 #       new_item = Item()
  #      new_item.name = request.POST.get('name')
   #     new_item.done = 'done' in request.POST
    #    new_item.save()
    #    
     #   return redirect(get_todo_list)
     
def edit_item(request, id):
    item = get_object_or_404(Item, pk=id)

    if request.method == "POST":
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect(get_todo_list)
    else:
        form = ItemForm(instance=item)
    return render(request, "item_form.html", {'form': form})
        
def toggle_status(request, id):
    item = get_object_or_404(Item, pk=id)
    item.done = not item.done
    item.save()
    return redirect(get_todo_list)
    
    
    
    
    
    

intro/templates/item_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Todo Add/Edit Items</title>
</head>
<body>
    <h1>Add NEW / Edit Item ...</h1>
    
    <form method="POST">
        
        {% csrf_token %}
        
<!-- Replaced by django forms       
        <label for="id_name">Name:</label><br>
        <input type="text" id="id_name" name="name"/><br>
        <br>
        <label for="id_done">Done:</label><br>
        <input type="checkbox" id="id_done" name="done"/><br>
        <br>
-->

        {{ form.as_p }}
        
        <button type="submit">Save</button>

    </form>
    
</body>
</html>

intro/templates/todo_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Todo List</title>
</head>
<body>
    <h1>Things to Do ...</h1>
    
    <table>
        {% for item in items %}
            <tr>
                {% if item.done %}
                <td><strike>{{ item.name }}</strike></td>
                {% else %}
                <td>{{ item.name }}</td>
                {% endif %}
                
                <td>
                    <form method="POST" action="toggle/{{ item.id }}">
                        {% csrf_token %}
                        <input type="submit" value="Toggle">
                    </form>
                </td>
                
                <td>
                    <form method="GET" action="edit/{{ item.id }}">
                        <input type="submit" value="Edit">
                    </form>
                </td>
            </tr>
            {% empty %}
            <p>You have nothing to do.</p>
        {% endfor %}
    </table>
    
    <a href="add"> Add an item</a>
    
</body>
</html>